apiVersion: apps/v1
kind: Deployment
metadata:
  name: try-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      containers:
        - name: wow-container
          image: nginx:latest
          ports:
            - containerPort: 80